version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: php:8.3-fpm
    container_name: app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: abol
      MYSQL_PASSWORD: abol
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge